parameters:
#    biber_ltd_core.example.class: BiberLtd\Bundle\CoreBundle\Example
services:
    input_validator:
        class:        BiberLtd\Bundle\CoreBundle\Services\InputValidator
        arguments:    ['@kernel']
    encryption:
        class:        BiberLtd\Bundle\CoreBundle\Services\Encryption
        arguments:    ['@kernel']
    buttonrender.model:
            class:        BiberLtd\Bundle\CoreBundle\Controller\ButtonRenderController
            arguments:    ['@templating.engine.delegating']
    corerender.model:
            class:        BiberLtd\Bundle\CoreBundle\Controller\RenderController
            arguments:    ['@templating.engine.delegating']
    emailrender.model:
            class:        BiberLtd\Bundle\CoreBundle\Controller\EmailRenderController
            arguments:    ['@templating.engine.delegating', '@kernel']
    formrender.model:
            class:        BiberLtd\Bundle\CoreBundle\Controller\FormRenderController
            arguments:    ['@templating.engine.delegating']
    htmlrender.model:
            class:        BiberLtd\Bundle\CoreBundle\Controller\HTMLRenderController
            arguments:    ['@templating.engine.delegating']
    tablerender.model:
            class:        BiberLtd\Bundle\CoreBundle\Controller\TableRenderController
            arguments:    ['@templating.engine.delegating', '@kernel']
    textarearender.model:
            class:        BiberLtd\Bundle\CoreBundle\Controller\FormRenderController
            arguments:    ['@templating.engine.delegating', '@kernel']
    typographyrender.model:
            class:        BiberLtd\Bundle\CoreBundle\Controller\TypographyRenderController
            arguments:    ['@templating.engine.delegating']
    widgetrender.model:
            class:        BiberLtd\Bundle\CoreBundle\Controller\WidgetRenderController
            arguments:    ['@templating.engine.delegating', '@kernel']
