parameters:
#    biber_ltd_core.example.class: BiberLtd\Bundle\CoreBundle\Example
services:
    encryption:
        class:        BiberLtd\Bundle\CoreBundle\Services\Encryption
        arguments:    ["@kernel"]