parameters:
#    biber_ltd_core.example.class: BiberLtd\Bundle\CoreBundle\Example

services:
#    biber_ltd_core.example:
#        class: %biber_ltd_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
